[pytest]
testpaths = tests
addopts = -v -s --alluredir=reports/allure --dist=loadgroup
importmode = importlib
pythonpath = .
log_cli = true
log_cli_level = INFO
markers =
    Regression: teste de regresie
    Smoke: teste de smoke
    order: ordinea de rulare a testelor